import pandas as pd
import plotly.express as px
import streamlit as st
from pathlib import Path


PROCESSED_DATA_PATH = Path("data/processed")


@st.cache_data
def load_processed_data():
    """
    Loads the processed dataset generated by the ETL pipeline.
    """
    clean_data = pd.read_csv(PROCESSED_DATA_PATH / "amazon_sales_clean.csv")

    clean_data["date"] = pd.to_datetime(clean_data["date"], errors="coerce")

    return clean_data


def apply_filters(df, selected_categories, selected_status, selected_states,
                  selected_customer_types, selected_fulfilment, date_range):
    """
    Applies dashboard filters to the processed dataset.
    """
    filtered_df = df.copy()

    if date_range and len(date_range) == 2:
        start_date = pd.to_datetime(date_range[0])
        end_date = pd.to_datetime(date_range[1])
        filtered_df = filtered_df[
            (filtered_df["date"] >= start_date) &
            (filtered_df["date"] <= end_date)
        ]

    if selected_categories:
        filtered_df = filtered_df[filtered_df["category"].isin(selected_categories)]

    if selected_status:
        filtered_df = filtered_df[filtered_df["order_status_group"].isin(selected_status)]

    if selected_states:
        filtered_df = filtered_df[filtered_df["ship_state"].isin(selected_states)]

    if selected_customer_types:
        filtered_df = filtered_df[filtered_df["customer_type"].isin(selected_customer_types)]

    if selected_fulfilment:
        filtered_df = filtered_df[filtered_df["fulfilment"].isin(selected_fulfilment)]

    return filtered_df


st.set_page_config(
    page_title="Amazon Sales DataOps Dashboard",
    page_icon="📊",
    layout="wide"
)


st.title("Amazon Sales DataOps Dashboard")

st.markdown(
    """
    Este dashboard muestra los principales indicadores comerciales y logísticos
    a partir de los datos procesados por el pipeline DataOps.
    """
)


try:
    clean_data = load_processed_data()
except FileNotFoundError:
    st.error(
        "No se han encontrado los datos procesados. "
        "Ejecuta primero el pipeline con: python src/pipeline.py"
    )
    st.stop()


# -------------------------------------------------------------------------
# SIDEBAR FILTERS
# -------------------------------------------------------------------------

st.sidebar.title("Panel de filtros")
st.sidebar.write("Selecciona los criterios para analizar los datos.")

if st.sidebar.button("Resetear filtros"):
    st.rerun()

min_date = clean_data["date"].min()
max_date = clean_data["date"].max()

date_range = st.sidebar.date_input(
    "Rango de fechas",
    value=(min_date, max_date),
    min_value=min_date,
    max_value=max_date
)

available_categories = sorted(clean_data["category"].dropna().unique())
selected_categories = st.sidebar.multiselect(
    "Categorías",
    available_categories,
    default=available_categories
)

available_status = sorted(clean_data["order_status_group"].dropna().unique())
selected_status = st.sidebar.multiselect(
    "Estado del pedido",
    available_status,
    default=available_status
)

available_states = sorted(clean_data["ship_state"].dropna().unique())
selected_states = st.sidebar.multiselect(
    "Regiones / estados",
    available_states,
    default=available_states
)

available_customer_types = sorted(clean_data["customer_type"].dropna().unique())
selected_customer_types = st.sidebar.multiselect(
    "Tipo de cliente",
    available_customer_types,
    default=available_customer_types
)

available_fulfilment = sorted(clean_data["fulfilment"].dropna().unique())
selected_fulfilment = st.sidebar.multiselect(
    "Tipo de fulfilment",
    available_fulfilment,
    default=available_fulfilment
)


filtered_data = apply_filters(
    clean_data,
    selected_categories,
    selected_status,
    selected_states,
    selected_customer_types,
    selected_fulfilment,
    date_range
)


# -------------------------------------------------------------------------
# EMPTY DATA CONTROL
# -------------------------------------------------------------------------

if filtered_data.empty:
    st.warning("No hay datos disponibles con los filtros seleccionados.")
    st.stop()


# -------------------------------------------------------------------------
# KPIs
# -------------------------------------------------------------------------

total_sales = filtered_data["amount"].sum()
total_orders = filtered_data["order_id"].nunique()
total_quantity = filtered_data["qty"].sum()
average_ticket = total_sales / total_orders if total_orders > 0 else 0
cancelled_orders = filtered_data[
    filtered_data["order_status_group"] == "Cancelled"
]["order_id"].nunique()
cancelled_rate = cancelled_orders / total_orders * 100 if total_orders > 0 else 0

st.subheader("Indicadores principales")

col1, col2, col3, col4, col5 = st.columns(5)

col1.metric("Ventas totales", f"{total_sales:,.2f}")
col2.metric("Pedidos", f"{total_orders:,}")
col3.metric("Unidades", f"{total_quantity:,.0f}")
col4.metric("Ticket medio", f"{average_ticket:,.2f}")
col5.metric("Cancelaciones", f"{cancelled_rate:.2f}%")


st.divider()


# -------------------------------------------------------------------------
# AGGREGATIONS
# -------------------------------------------------------------------------

sales_by_date = (
    filtered_data
    .dropna(subset=["date"])
    .groupby("date", as_index=False)
    .agg(
        total_sales=("amount", "sum"),
        total_orders=("order_id", "nunique"),
        total_quantity=("qty", "sum")
    )
    .sort_values("date")
)

sales_by_category = (
    filtered_data
    .groupby("category", as_index=False)
    .agg(
        total_sales=("amount", "sum"),
        total_orders=("order_id", "nunique"),
        total_quantity=("qty", "sum")
    )
    .sort_values("total_sales", ascending=False)
)

sales_by_status = (
    filtered_data
    .groupby("order_status_group", as_index=False)
    .agg(
        total_orders=("order_id", "nunique"),
        total_sales=("amount", "sum")
    )
    .sort_values("total_orders", ascending=False)
)

sales_by_state = (
    filtered_data
    .groupby("ship_state", as_index=False)
    .agg(
        total_sales=("amount", "sum"),
        total_orders=("order_id", "nunique")
    )
    .sort_values("total_sales", ascending=False)
    .head(10)
)

sales_by_customer_type = (
    filtered_data
    .groupby("customer_type", as_index=False)
    .agg(
        total_sales=("amount", "sum"),
        total_orders=("order_id", "nunique")
    )
)

sales_by_fulfilment = (
    filtered_data
    .groupby("fulfilment", as_index=False)
    .agg(
        total_sales=("amount", "sum"),
        total_orders=("order_id", "nunique")
    )
    .sort_values("total_orders", ascending=False)
)


# -------------------------------------------------------------------------
# CHARTS
# -------------------------------------------------------------------------

st.subheader("Evolución temporal")

metric_to_plot = st.selectbox(
    "Selecciona la métrica temporal",
    options=["total_sales", "total_orders", "total_quantity"],
    format_func={
        "total_sales": "Ventas totales",
        "total_orders": "Número de pedidos",
        "total_quantity": "Unidades vendidas"
    }.get
)

fig_time = px.line(
    sales_by_date,
    x="date",
    y=metric_to_plot,
    markers=True,
    title="Evolución temporal de la métrica seleccionada",
    labels={
        "date": "Fecha",
        "total_sales": "Ventas totales",
        "total_orders": "Número de pedidos",
        "total_quantity": "Unidades vendidas"
    }
)

fig_time.update_layout(
    xaxis_title="Fecha",
    yaxis_title="Valor",
    hovermode="x unified"
)

st.plotly_chart(fig_time, use_container_width=True)


col_left, col_right = st.columns(2)

with col_left:
    st.subheader("Ventas por categoría")

    fig_category = px.bar(
        sales_by_category,
        x="category",
        y="total_sales",
        text_auto=".2s",
        title="Ventas totales por categoría",
        labels={
            "category": "Categoría",
            "total_sales": "Ventas totales"
        }
    )

    fig_category.update_layout(
        xaxis_title="Categoría",
        yaxis_title="Ventas totales"
    )

    st.plotly_chart(fig_category, use_container_width=True)


with col_right:
    st.subheader("Pedidos por estado")

    fig_status = px.pie(
        sales_by_status,
        names="order_status_group",
        values="total_orders",
        title="Distribución de pedidos por estado",
        hole=0.4
    )

    st.plotly_chart(fig_status, use_container_width=True)


col_left, col_right = st.columns(2)

with col_left:
    st.subheader("Top 10 regiones por ventas")

    fig_state = px.bar(
        sales_by_state,
        x="total_sales",
        y="ship_state",
        orientation="h",
        text_auto=".2s",
        title="Regiones con mayor volumen de ventas",
        labels={
            "ship_state": "Región",
            "total_sales": "Ventas totales"
        }
    )

    fig_state.update_layout(
        yaxis={"categoryorder": "total ascending"}
    )

    st.plotly_chart(fig_state, use_container_width=True)


with col_right:
    st.subheader("Ventas por tipo de cliente")

    fig_customer = px.bar(
        sales_by_customer_type,
        x="customer_type",
        y="total_sales",
        text_auto=".2s",
        title="Comparación entre clientes B2B y B2C",
        labels={
            "customer_type": "Tipo de cliente",
            "total_sales": "Ventas totales"
        }
    )

    st.plotly_chart(fig_customer, use_container_width=True)


st.subheader("Análisis de fulfilment")

fig_fulfilment = px.bar(
    sales_by_fulfilment,
    x="fulfilment",
    y="total_orders",
    text_auto=True,
    title="Número de pedidos según tipo de fulfilment",
    labels={
        "fulfilment": "Tipo de fulfilment",
        "total_orders": "Número de pedidos"
    }
)

st.plotly_chart(fig_fulfilment, use_container_width=True)


# -------------------------------------------------------------------------
# DATA TABLE AND DOWNLOAD
# -------------------------------------------------------------------------

st.divider()

st.subheader("Datos filtrados")

st.write(
    f"Mostrando una muestra de los datos filtrados. "
    f"Registros disponibles: {len(filtered_data):,}"
)

st.dataframe(filtered_data.head(500), use_container_width=True)

csv = filtered_data.to_csv(index=False).encode("utf-8")

st.download_button(
    label="Descargar datos filtrados en CSV",
    data=csv,
    file_name="amazon_sales_filtered.csv",
    mime="text/csv"
)